name: CI/CD

on:
  push:
    branches:
      - main # Change to the branch you want to monitor for changes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Deploy to GitHub Pages
        if: success()
        run: |
          npm run build  # Générer les fichiers de production
          npx gh-pages -d build  # Déployer le dossier "build" sur GitHub Pages
